[workspace]
resolver = "2"
members = [
    "proxmox-auto-installer",
    "proxmox-auto-install-assistant",
    "proxmox-chroot",
    "proxmox-fetch-answer",
    "proxmox-installer-common",
    "proxmox-tui-installer",
]

