package Proxmox::Install::Distro;

# Distribution backend for the low-level installer.
#
# All distribution-specific actions are funneled through this module so that
# Proxmox/Install.pm keeps a generic, distro-neutral orchestration flow.
# Each exported function dispatches at runtime between a Debian/dpkg path and
# an openEuler/RPM path based on whether `apt` is present inside $targetdir.
# This mirrors the detection used by unconfigured.sh and setup_root_password.

use strict;
use warnings;

use Proxmox::Sys::Command qw(run_command syscmd);
use Proxmox::Sys::File qw(file_read_all file_write_all);

use base qw(Exporter);

our @EXPORT_OK = qw(
    is_debian
    prepare_chroot_env
    cleanup_chroot_env
    remove_boot_diversions
    debconfig_set
    pkg_install_all
    mkinitramfs
    grub_mkconfig
    grub_install_bios
    grub_install_efi
    proxmox_boot_mode
    append_grub_default
    set_grub_cmdline
    write_repo
    list_installed
);

# Path of the grub config generated by grub2-mkconfig on openEuler.
our $GRUB_CFG_RPM = '/boot/grub2/grub.cfg';

my $EFI_TARGET = {
    'x86_64' => 'x86_64-efi',
    'aarch64' => 'arm64-efi',
    'loongarch64' => 'loongarch64-efi',
    'riscv64' => 'riscv64-efi',
};

# Detected once per process. $targetdir is the same value across the whole
# extract_data flow ("/target" or "target" in test mode), so caching is safe.
my $_is_debian_cache;
sub is_debian {
    my ($targetdir) = @_;
    return $_is_debian_cache if defined $_is_debian_cache;
    $_is_debian_cache = (-e "$targetdir/usr/bin/apt") ? 1 : 0;
    return $_is_debian_cache;
}

# --- dpkg-divert helpers (Debian-only, used by prepare/cleanup_chroot_env) ---

sub _dpkg_divert_add {
    my ($targetdir, $cmd, $new_cmd) = @_;

    syscmd("chroot $targetdir dpkg-divert --package proxmox --add --rename $cmd") == 0
        || die "unable to exec dpkg-divert\n";

    syscmd("ln -sf ${new_cmd} $targetdir/$cmd") == 0
        || die "unable to link diversion to ${new_cmd}\n";
}

sub _dpkg_divert_remove {
    my ($targetdir, $cmd) = @_;

    syscmd("mv $targetdir/${cmd}.distrib $targetdir/${cmd};") == 0
        || die "unable to remove $cmd diversion\n";

    syscmd("chroot $targetdir dpkg-divert --remove $cmd") == 0
        || die "unable to remove $cmd diversion\n";
}

# Prepare the chroot for package installation.
#
# On Debian, daemons started by maintainer scripts and update-grub /
# update-initramfs triggers would all fire inside the chroot, which we have to
# suppress: drop in a policy-rc.d that refuses to start services, replace
# start-stop-daemon with a stub, and divert update-grub / update-initramfs to
# /bin/true (we regenerate both explicitly at the end).
#
# On openEuler, RPM scriptlets do not start services from inside a chroot and
# do not trigger grub/initramfs regeneration during install, so this is a no-op.
sub prepare_chroot_env {
    my ($targetdir, $proxmox_libdir) = @_;

    return if !is_debian($targetdir);

    syscmd("cp ${proxmox_libdir}/policy-disable-rc.d $targetdir/usr/sbin/policy-rc.d") == 0
        || die "unable to copy policy-rc.d\n";
    syscmd("cp ${proxmox_libdir}/fake-start-stop-daemon $targetdir/sbin/") == 0
        || die "unable to copy start-stop-daemon\n";

    _dpkg_divert_add($targetdir, "/sbin/start-stop-daemon", "/sbin/fake-start-stop-daemon");
    _dpkg_divert_add($targetdir, "/usr/sbin/update-grub", "/bin/true");
    _dpkg_divert_add($targetdir, "/usr/sbin/update-initramfs", "/bin/true");
}

# Reverse the grub/initramfs diversions so the real binaries can run once.
# The start-stop-daemon diversion is removed separately by
# cleanup_chroot_env_late() after the bootloader has been installed.
sub _remove_boot_diversions {
    my ($targetdir) = @_;
    _dpkg_divert_remove($targetdir, "/usr/sbin/update-grub");
    _dpkg_divert_remove($targetdir, "/usr/sbin/update-initramfs");
}

# Final cleanup of chroot suppression: remove the start-stop-daemon diversion
# and the policy-rc.d drop-in.
sub cleanup_chroot_env {
    my ($targetdir) = @_;

    if (is_debian($targetdir)) {
        _dpkg_divert_remove($targetdir, "/sbin/start-stop-daemon");
    }
    unlink "$targetdir/usr/sbin/policy-rc.d";
}

# Apply debconf preseed data to the chroot.
# On openEuler, debconf does not exist; equivalent settings (locale/keymap/grub
# install devices) are applied via openEuler mechanisms elsewhere when needed.
sub debconfig_set {
    my ($targetdir, $dcdata) = @_;

    return if !is_debian($targetdir);

    my $cfgfile = "/tmp/debconf.txt";
    file_write_all("$targetdir/$cfgfile", $dcdata);
    syscmd("chroot $targetdir debconf-set-selections $cfgfile");
    unlink "$targetdir/$cfgfile";
}

# Install all product packages.
#
# $opts is a hashref with:
#   pkgdir              host-side directory containing *.deb / *.rpm (bind-mounted at /tmp/pkg)
#   use_btrfs           pass --force-unsafe-io to dpkg on btrfs (slow without it)
#   boot_type           'efi' or 'bios' (Debian only: pick the right grub package)
#   secure_boot         truthy if the host booted with Secure Boot enabled
#   first_boot_enabled  truthy to include proxmox-first-boot
#   progress_cb         optional sub: ->($msg, $done, $total, $phase)
#                       $phase is 'unpack' (install/extract) or 'configure'
#                       (post-install setup / verify); caller maps these to
#                       distinct visual progress ranges
#
# Mirrors the original Debian intent: the base squashfs already provides all
# dependencies, so packages are installed without re-resolving against a repo
# (dpkg --force-depends / rpm --nodeps).
sub pkg_install_all {
    my ($targetdir, $opts) = @_;

    if (is_debian($targetdir)) {
        _pkg_install_all_deb($targetdir, $opts);
    } else {
        _pkg_install_all_rpm($targetdir, $opts);
    }
}

sub _pkg_install_all_deb {
    my ($targetdir, $opts) = @_;

    my $pkgdir = $opts->{pkgdir} // die "pkg_install_all: pkgdir required on Debian\n";
    my $progress_cb = $opts->{progress_cb};

    my $pkg_count = 0;
    while (<${pkgdir}/*.deb>) { $pkg_count++ };

    # btrfs/dpkg is extremely slow without --force-unsafe-io
    my $dpkg_opts = $opts->{use_btrfs} ? "--force-unsafe-io" : "";

    my $count = 0;
    while (<${pkgdir}/*.deb>) {
        chomp;
        my $path = $_;
        my ($deb) = $path =~ m/${pkgdir}\/(.*\.deb)/;

        # the grub-pc/grub-efi-amd64 packages (w/o -bin) are the ones actually
        # updating grub upon upgrade - and conflict with each other - install
        # the fitting one only
        next if ($deb =~ /grub-pc_/ && ($opts->{boot_type} // '') ne 'bios');
        next if ($deb =~ /grub-efi-amd64_/ && ($opts->{boot_type} // '') ne 'efi');
        next if ($deb =~ /^proxmox-grub/ && ($opts->{boot_type} // '') ne 'efi');
        next if ($deb =~ /^proxmox-secure-boot-support_/ && !$opts->{secure_boot});
        next if ($deb =~ /^proxmox-first-boot/ && !$opts->{first_boot_enabled});

        # pre-tick: announce with text at current $count
        $progress_cb->("extracting $deb", $count, $pkg_count, 'unpack') if $progress_cb;

        syscmd("chroot $targetdir dpkg $dpkg_opts --force-depends --no-triggers --unpack /tmp/pkg/$deb") == 0
            || die "installation of package $deb failed\n";

        # post-tick: advance the bar after success (no text); mirrors original
        $count++;
        $progress_cb->(undef, $count, $pkg_count, 'unpack') if $progress_cb;
    }

    # needed for postfix postinst in case no other NIC is active
    syscmd("chroot $targetdir ifup lo");

    my $cmd = "chroot $targetdir dpkg $dpkg_opts --force-confold --configure -a";
    my $cfg_count = 0;
    run_command($cmd, sub {
        my $line = shift;
        if ($line =~ m/Setting up\s+(\S+)/) {
            $progress_cb->("configuring $1", ++$cfg_count, $pkg_count, 'configure') if $progress_cb;
        }
        return;
    });
}

sub _pkg_install_all_rpm {
    my ($targetdir, $opts) = @_;

    my $pkgdir = $opts->{pkgdir};
    my $progress_cb = $opts->{progress_cb};

    # pre-count *.rpm for the progress denominator (host-side path; same
    # directory that's bind-mounted at /tmp/pkg inside the chroot)
    my $pkg_count = 0;
    if ($pkgdir) {
        while (<${pkgdir}/*.rpm>) { $pkg_count++ };
    }
    $pkg_count ||= 1;   # avoid div-by-zero in the callback

    my $helper = '/usr/bin/pve-rpm-transaction';
    if (!-x $helper) {
        # fallback for older ISO environments without the helper; keep the
        # single rpm transaction, but parse rpm's human-readable output.
        my $cmd = "chroot $targetdir /bin/sh -c 'rpm -Uvh --replacepkgs --nodeps /tmp/pkg/*.rpm'";
        my $phase = 'install';
        my $res = run_command($cmd, sub {
            my $line = shift;
            return if !$progress_cb;

            if ($line =~ /^Preparing/i) {
                $progress_cb->("preparing packages", 0, $pkg_count, 'unpack');
            } elsif ($line =~ m{^Updating\s*/\s*installing}i || $line =~ /^Installing/i) {
                $phase = 'install';
            } elsif ($line =~ /^Verifying/i) {
                $phase = 'verify';
            } elsif ($line =~ /^\s*(\d+):(\S+)/) {
                my ($n, $name) = ($1, $2);
                if ($phase eq 'verify') {
                    $progress_cb->("verifying $name", $n, $pkg_count, 'configure');
                } else {
                    $progress_cb->("installing $name", $n, $pkg_count, 'unpack');
                }
            }
            return;
        }, undef, 1);
        $res == 0 || die "installation of product RPM packages failed\n";
        return;
    }

    # `pve-rpm-transaction` lets rpm order the set internally. --nodeps
    # mirrors dpkg's --force-depends: deps come from the base squashfs.
    my $cmd = "$helper --root $targetdir --replacepkgs --nodeps ${pkgdir}/*.rpm";

    my $res = run_command($cmd, sub {
        my $line = shift;
        return if !$progress_cb;

        return if $line !~ /^PVE-RPM\t/;

        if ($line =~ /^PVE-RPM\tprogress\t(\S+)\t(\d+)\t(\d+)\t(.+)$/) {
            my ($phase, $done, $total, $name) = ($1, $2, $3, $4);

            # rpm emits a burst of verify callbacks before any package install starts.
            return if $phase eq 'verify' && $done == 0;

            my $verb = $phase eq 'configure' ? 'configuring'
                : $phase eq 'verify' ? 'verifying'
                : 'installing';
            my $ui_phase = $phase eq 'configure' ? 'configure' : 'unpack';

            $progress_cb->("$verb $name", $done, $total, $ui_phase);
        }
        return;
    }, undef, 1);
    $res == 0 || die "installation of product RPM packages failed\n";
}

# Regenerate the initramfs for all installed kernels.
sub mkinitramfs {
    my ($targetdir) = @_;

    if (is_debian($targetdir)) {
        syscmd("chroot $targetdir /usr/sbin/update-initramfs -c -k all") == 0
            || die "unable to install initramfs\n";
    } else {
        # dracut runs from a chroot while /proc still describes the live installer
        # environment, so hostonly detection can miss the target root stack.
        syscmd("chroot $targetdir /usr/bin/dracut --regenerate-all --no-hostonly"
            . " --force-add 'lvm dm btrfs' --force") == 0
            || die "unable to regenerate initramfs (dracut)\n";
    }
}

# Regenerate the grub boot menu from /etc/default/grub + /etc/grub.d/*.
sub grub_mkconfig {
    my ($targetdir) = @_;

    if (is_debian($targetdir)) {
        syscmd("chroot $targetdir /usr/sbin/update-grub") == 0
            || die "unable to update boot loader config\n";
    } else {
        syscmd("chroot $targetdir /usr/sbin/grub2-mkconfig -o $GRUB_CFG_RPM") == 0
            || die "unable to update boot loader config (grub2-mkconfig)\n";
    }
}

# Install the grub BIOS/legacy core to a disk's MBR + BIOS-boot partition.
# Returns the syscmd return code (0 == success).
sub grub_install_bios {
    my ($targetdir, $dev, $bootloader_id) = @_;

    if (is_debian($targetdir)) {
        $bootloader_id //= 'proxmox';
        return syscmd("chroot $targetdir /usr/sbin/grub-install"
            . " --target i386-pc --no-floppy --bootloader-id='$bootloader_id' $dev");
    } else {
        $bootloader_id //= 'pxvirt';
        return syscmd("chroot $targetdir /usr/sbin/grub2-install"
            . " --target i386-pc --no-floppy --bootloader-id='$bootloader_id' $dev");
    }
}

# Install the grub EFI core for the given host architecture onto the ESP.
# Returns the syscmd return code (0 == success).
sub grub_install_efi {
    my ($targetdir, $dev, $arch, $bootloader_id) = @_;

    my $target = $EFI_TARGET->{$arch}
        or die "unable to install grub on arch $arch\n";

    if (is_debian($targetdir)) {
        $bootloader_id //= 'lierfang';
        return syscmd("chroot $targetdir /usr/sbin/grub-install"
            . " --target $target --no-floppy --bootloader-id='$bootloader_id' $dev");
    } else {
        $bootloader_id //= 'pxvirt';
        # openEuler grub2 ships a grubenv symlink that grub2-install fails to
        # write through; remove it so the install can recreate a fresh file.
        syscmd("rm -f $targetdir/boot/grub2/grubenv");
        return syscmd("chroot $targetdir /usr/sbin/grub2-install"
            . " --target $target --no-floppy --bootloader-id='$bootloader_id' $dev");
    }
}

# Pick the proxmox-boot-tool mode to initialize an ESP with.
#
# Debian default is grub-on-ESP only under Secure Boot; otherwise an empty
# string lets proxmox-boot-tool default to systemd-boot. openEuler always uses
# grub-on-ESP because systemd-boot is not part of the supported flow.
sub proxmox_boot_mode {
    my ($targetdir, $secureboot) = @_;

    if (is_debian($targetdir)) {
        return $secureboot ? 'grub' : '';
    } else {
        return 'grub';
    }
}

# Append a grub default snippet.
#
# Debian: write it as a separate drop-in /etc/default/grub.d/$name so that the
# original /etc/default/grub stays untouched (update-grub sources the dir).
# openEuler: grub2-mkconfig does NOT source /etc/default/grub.d/*, so fold the
# snippet into the single /etc/default/grub file instead. $name is ignored.
sub append_grub_default {
    my ($targetdir, $name, $text) = @_;

    if (is_debian($targetdir)) {
        file_write_all("$targetdir/etc/default/grub.d/$name", $text);
    } else {
        my $fn = "$targetdir/etc/default/grub";
        my $content = -e $fn ? file_read_all($fn) : '';
        $content .= "\n" if length($content) && $content !~ /\n\z/;
        $content .= "$text\n";
        file_write_all($fn, $content);
    }
}

# Append extra kernel parameters to GRUB_CMDLINE_LINUX. Because grub's defaults
# file is sourced as shell top-to-bottom, a trailing assignment that references
# the existing value cleanly appends to it.
sub set_grub_cmdline {
    my ($targetdir, $name, $cmdline) = @_;

    append_grub_default(
        $targetdir, $name,
        "GRUB_CMDLINE_LINUX=\"\$GRUB_CMDLINE_LINUX $cmdline\"",
    );
}

# Write the post-install package repository for the target system.
sub write_repo {
    my ($targetdir, $mirror) = @_;

    if (is_debian($targetdir)) {
        # apply optional country-specific mirror to the shipped sources.list,
        # and create extended_states so apt's cron job does not warn.
        if ($mirror) {
            my $fn = "$targetdir/etc/apt/sources.list";
            syscmd("sed -i 's/ftp\\.debian\\.org/$mirror/' '$fn'");
        }
        file_write_all("$targetdir/var/lib/apt/extended_states", '');
    } else {
        $mirror //= 'https://repo.pxvirt.org/openeuler';
        my $repo = <<"_EOF_";
[pxvirt]
name=PXVIRT
baseurl=$mirror
enabled=1
gpgcheck=0
_EOF_
        file_write_all("$targetdir/etc/yum.repos.d/pxvirt.repo", $repo);
    }
}

# Record the final list of installed packages into $outfile (path relative to
# the current working directory, matching the original "final.pkglist" usage).
sub list_installed {
    my ($targetdir, $outfile) = @_;
    $outfile //= 'final.pkglist';

    if (is_debian($targetdir)) {
        syscmd("chroot $targetdir /usr/bin/dpkg-query -W --showformat='\${package}\n'> $outfile");
    } else {
        my $list = '';
        run_command(
            "chroot $targetdir /usr/bin/rpm -qa --qf '%{NAME}\n'",
            sub { $list .= "$_[0]\n"; },
        );
        file_write_all($outfile, $list);
    }
}

# Exported wrapper so Install.pm can invoke "remove boot diversions" cleanly
# without poking at a private name. No-op on openEuler.
sub remove_boot_diversions {
    my ($targetdir) = @_;
    _remove_boot_diversions($targetdir) if is_debian($targetdir);
}

1;
